"""
===============================================================================
Enterprise Revenue Intelligence Platform (ERIP)
===============================================================================

Module      : base_presenter.py
Package     : src.presentation
Purpose     : Enterprise Base Presenter
Author      : ERIP
Version     : 3.0.0

Description
-----------
Abstract base class for all Enterprise Presentation components.

The BasePresenter defines the common presentation contract used by
Runtime, Warehouse, Semantic, Monitoring and Quality presenters.

Responsibilities
----------------
- Define rendering contract
- Provide display capability
- Provide shared rendering helpers
- Eliminate duplicated presentation logic

===============================================================================
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any

from .console import Console


# =============================================================================
# Base Presenter
# =============================================================================


class BasePresenter(ABC):
    """
    Base class for all Enterprise presenters.

    Presenters are stateless services responsible for transforming
    domain models into enterprise operational reports.
    """

    # -------------------------------------------------------------------------
    # Rendering Contract
    # -------------------------------------------------------------------------

    @classmethod
    @abstractmethod
    def render(
        cls,
        model: Any,
    ) -> str:
        """
        Build a formatted report.

        Returns
        -------
        str
            Rendered report.
        """

        raise NotImplementedError

    # -------------------------------------------------------------------------
    # Display
    # -------------------------------------------------------------------------

    @staticmethod
    def display(
        report: str,
    ) -> None:
        """
        Display a rendered report.

        Parameters
        ----------
        report
            Report generated by a presenter.
        """

        Console.display(report)

    # -------------------------------------------------------------------------
    # Convenience
    # -------------------------------------------------------------------------

    @classmethod
    def present(
        cls,
        model: Any,
    ) -> None:
        """
        Render and immediately display a report.

        Parameters
        ----------
        model
            Domain model to present.
        """

        cls.display(

            cls.render(model)

        )

    # -------------------------------------------------------------------------
    # Shared Helpers
    # -------------------------------------------------------------------------

    @staticmethod
    def metadata(
        metadata: dict[str, Any] | None,
    ) -> str:
        """
        Build a formatted metadata section.
        """

        if not metadata:

            return "No metadata available."

        return Console.join(

            *(
                Console.key_value(

                    str(key),

                    value,

                )

                for key, value in metadata.items()

            )

        )